// mock data mostly based on http://api.football-data.org

export default {
  GetAllAreas: async () => {
    const data = {
      count: 4,
      filters: {},
      areas: [
        {
          id: 2072,
          name: "England",
          countryCode: "ENG",
          flag: "https://crests.football-data.org/770.svg",
          parentAreaId: 2077,
          parentArea: "Europe",
        },
        {
          id: 2088,
          name: "Germany",
          countryCode: "DEU",
          flag: "https://crests.football-data.org/759.svg",
          parentAreaId: 2077,
          parentArea: "Europe",
        },
        {
          id: 2081,
          name: "France",
          countryCode: "FRA",
          flag: "https://crests.football-data.org/773.svg",
          parentAreaId: 2077,
          parentArea: "Europe",
        },
        {
          id: 2032,
          name: "Brazil",
          countryCode: "BRA",
          flag: "https://crests.football-data.org/764.svg",
          parentAreaId: 2220,
          parentArea: "South America",
        },
      ],
    };
    console.log("RES GetAllAreas ", data);
    return data;
  },
  GetAreaTeams: async (payload) => {
    console.log("REQ GetAreaTeams ", payload);
    const dataENG = {
      filters: {
        season: "2022",
      },
      competition: {
        id: 2021,
        name: "Premier League",
        code: "PL",
        country: "England",
        type: "LEAGUE",
        emblem: "https://crests.football-data.org/PL.png",
      },
      season: {
        id: 1490,
        startDate: "2022-08-05",
        endDate: "2023-05-28",
        currentMatchday: 21,
        winner: null,
      },
      teams: [
        {
          area: {
            id: 2072,
            name: "England",
            code: "ENG",
            flag: "https://crests.football-data.org/770.svg",
          },
          id: 57,
          name: "Arsenal FC",
          shortName: "Arsenal",
          tla: "ARS",
          crest: "https://crests.football-data.org/57.png",
          address: "75 Drayton Park London N5 1BU",
          website: "http://www.arsenal.com",
          founded: 1886,
          clubColors: "Red / White",
          venue: "Emirates Stadium",
        },
        {
          area: {
            id: 2072,
            name: "England",
            code: "ENG",
            flag: "https://crests.football-data.org/770.svg",
          },
          id: 58,
          name: "Aston Villa FC",
          shortName: "Aston Villa",
          tla: "AVL",
          crest: "https://crests.football-data.org/58.png",
          address: "Villa Park Birmingham B6 6HE",
          website: "http://www.avfc.co.uk",
          founded: 1872,
          clubColors: "Claret / Sky Blue",
          venue: "Villa Park",
        },
        {
          area: {
            id: 2072,
            name: "England",
            code: "ENG",
            flag: "https://crests.football-data.org/770.svg",
          },
          id: 61,
          name: "Chelsea FC",
          shortName: "Chelsea",
          tla: "CHE",
          crest: "https://crests.football-data.org/61.png",
          address: "Fulham Road London SW6 1HS",
          website: "http://www.chelseafc.com",
          founded: 1905,
          clubColors: "Royal Blue / White",
          venue: "Stamford Bridge",
        },
        {
          area: {
            id: 2072,
            name: "England",
            code: "ENG",
            flag: "https://crests.football-data.org/770.svg",
          },
          id: 62,
          name: "Everton FC",
          shortName: "Everton",
          tla: "EVE",
          crest: "https://crests.football-data.org/62.png",
          address: "Goodison Park Liverpool L4 4EL",
          website: "http://www.evertonfc.com",
          founded: 1878,
          clubColors: "Blue / White",
          venue: "Goodison Park",
        },
        {
          area: {
            id: 2072,
            name: "England",
            code: "ENG",
            flag: "https://crests.football-data.org/770.svg",
          },
          id: 63,
          name: "Fulham FC",
          shortName: "Fulham",
          tla: "FUL",
          crest: "https://crests.football-data.org/63.svg",
          address: "Craven Cottage, Stevenage Road London SW6 6HH",
          website: "http://www.fulhamfc.com",
          founded: 1879,
          clubColors: "White / Black",
          venue: "Craven Cottage",
        },
        {
          area: {
            id: 2072,
            name: "England",
            code: "ENG",
            flag: "https://crests.football-data.org/770.svg",
          },
          id: 64,
          name: "Liverpool FC",
          shortName: "Liverpool",
          tla: "LIV",
          crest: "https://crests.football-data.org/64.png",
          address: "Anfield Road Liverpool L4 0TH",
          website: "http://www.liverpoolfc.tv",
          founded: 1892,
          clubColors: "Red / White",
          venue: "Anfield",
        },
        {
          area: {
            id: 2072,
            name: "England",
            code: "ENG",
            flag: "https://crests.football-data.org/770.svg",
          },
          id: 65,
          name: "Manchester City FC",
          shortName: "Man City",
          tla: "MCI",
          crest: "https://crests.football-data.org/65.png",
          address: "SportCity Manchester M11 3FF",
          website: "https://www.mancity.com",
          founded: 1880,
          clubColors: "Sky Blue / White",
          venue: "Etihad Stadium",
        },
        {
          area: {
            id: 2072,
            name: "England",
            code: "ENG",
            flag: "https://crests.football-data.org/770.svg",
          },
          id: 66,
          name: "Manchester United FC",
          shortName: "Man United",
          tla: "MUN",
          crest: "https://crests.football-data.org/66.png",
          address: "Sir Matt Busby Way Manchester M16 0RA",
          website: "http://www.manutd.com",
          founded: 1878,
          clubColors: "Red / White",
          venue: "Old Trafford",
        },
        {
          area: {
            id: 2072,
            name: "England",
            code: "ENG",
            flag: "https://crests.football-data.org/770.svg",
          },
          id: 67,
          name: "Newcastle United FC",
          shortName: "Newcastle",
          tla: "NEW",
          crest: "https://crests.football-data.org/67.png",
          address: "Sports Direct Arena Newcastle upon Tyne NE1 4ST",
          website: "http://www.nufc.co.uk",
          founded: 1881,
          clubColors: "Black / White",
          venue: "St. James' Park",
        },
        {
          area: {
            id: 2072,
            name: "England",
            code: "ENG",
            flag: "https://crests.football-data.org/770.svg",
          },
          id: 354,
          name: "Crystal Palace FC",
          shortName: "Crystal Palace",
          tla: "CRY",
          crest: "https://crests.football-data.org/354.png",
          address: "Whitehorse Lane London SE25 6PU",
          website: "http://www.cpfc.co.uk",
          founded: 1905,
          clubColors: "Red / Blue",
          venue: "Selhurst Park",
        },
        {
          area: {
            id: 2072,
            name: "England",
            code: "ENG",
            flag: "https://crests.football-data.org/770.svg",
          },
          id: 397,
          name: "Brighton & Hove Albion FC",
          shortName: "Brighton Hove",
          tla: "BHA",
          crest: "https://crests.football-data.org/397.svg",
          address: "44 North Road Brighton & Hove BN1 1YR",
          website: "http://www.seagulls.co.uk",
          founded: 1898,
          clubColors: "Blue / White",
          venue: "The American Express Community Stadium",
        },
      ],
    };
    const dataOther = {
      count: 18,
      filters: {
        season: "2022",
      },
      competition: {
        id: 2002,
        name: "Bundesliga",
        code: "BL1",
        country: "Germany",
        type: "LEAGUE",
        emblem: "https://crests.football-data.org/BL1.png",
      },
      season: {
        id: 1495,
        startDate: "2022-08-05",
        endDate: "2023-05-27",
        currentMatchday: 16,
        winner: null,
      },
      teams: [
        {
          area: {
            id: 2088,
            name: "Germany",
            code: "DEU",
            flag: "https://crests.football-data.org/759.svg",
          },
          id: 1,
          name: "1. FC Köln",
          shortName: "1. FC Köln",
          tla: "KOE",
          crest: "https://crests.football-data.org/1.png",
          address: "Franz-Kremer-Allee 1 Köln 50937",
          website: "http://www.fc-koeln.de",
          founded: 1948,
          clubColors: "Red / White",
          venue: "RheinEnergieSTADION",
        },
        {
          area: {
            id: 2088,
            name: "Germany",
            code: "DEU",
            flag: "https://crests.football-data.org/759.svg",
          },
          id: 2,
          name: "TSG 1899 Hoffenheim",
          shortName: "Hoffenheim",
          tla: "TSG",
          crest: "https://crests.football-data.org/2.png",
          address: "Horrenberger Straße 58 Zuzenhausen 74939",
          website: "http://www.achtzehn99.de",
          founded: 1921,
          clubColors: "Blue / White",
          venue: "PreZero Arena",
        },
        {
          area: {
            id: 2088,
            name: "Germany",
            code: "DEU",
            flag: "https://crests.football-data.org/759.svg",
          },
          id: 3,
          name: "Bayer 04 Leverkusen",
          shortName: "Leverkusen",
          tla: "B04",
          crest: "https://crests.football-data.org/3.png",
          address: "Bismarckstr. 122-124 Leverkusen 51373",
          website: "http://www.bayer04.de",
          founded: 1904,
          clubColors: "Red / White / Black",
          venue: "BayArena",
        },
        {
          area: {
            id: 2088,
            name: "Germany",
            code: "DEU",
            flag: "https://crests.football-data.org/759.svg",
          },
          id: 4,
          name: "Borussia Dortmund",
          shortName: "Dortmund",
          tla: "BVB",
          crest: "https://crests.football-data.org/4.png",
          address: "Rheinlanddamm 207-209 Dortmund 44137",
          website: "http://www.bvb.de",
          founded: 1909,
          clubColors: "Black / Yellow",
          venue: "Signal Iduna Park",
        },
        {
          area: {
            id: 2088,
            name: "Germany",
            code: "DEU",
            flag: "https://crests.football-data.org/759.svg",
          },
          id: 5,
          name: "FC Bayern München",
          shortName: "Bayern",
          tla: "FCB",
          crest: "https://crests.football-data.org/5.svg",
          address: "Säbenerstr. 51 München 81547",
          website: "http://www.fcbayern.de",
          founded: 1900,
          clubColors: "Red / White / Blue",
          venue: "Allianz Arena",
        },
      ],
    };

    let res = "";

    if (payload === "ENG") {
      res = dataENG;
    } else {
      res = dataOther;
    }

    console.log("RES GetAreaTeams ", res);
    return res;
  },
};
